#pragma once
#include "core.h"

#define ctl_read    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0111, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define ctl_write    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0222, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

#define ctl_alloc   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0333, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)
#define ctl_free   CTL_CODE(FILE_DEVICE_UNKNOWN, 0x0444, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)